version: "3.8"
services:

  backend_module_project_3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1111:1111"
    restart: unless-stopped
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env
    #docker-compose run --rm backend_module_project_3 private_library library-filling
#  cli:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: unless-stopped
#    depends_on:
#      - db
#      - rabbitmq
#    env_file:
#      - .env
#    entrypoint: ['private_library', 'library_filling']


  db:
    image: postgres:14
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/db
    env_file:
        - .env

  nginx:
    image: nginx:1.21.6
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [ nginx-debug, '-g', 'daemon off;' ]
    restart: unless-stopped
    links:
      - backend_module_project_3
    ports:
      - "8880:8880"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - ./rabbitmq_data:/data
