@startuml
header Демо проект "частная библиотека"
title Диаграмма компонентов


rectangle "Interfaces (Primary Adapters)" {
  [Library API] as lib_api
  [Rabbitmq consumer] as rabbitmq_consumer
}

rectangle "Application" {
  [Library] as library
  interface "Library repositories" as library_repositories
  interface "Library publisher" as library_publisher
}

rectangle "Adapters (Secondary Adapters)" {
  [Database] as database
  [Publisher] as publisher
}

() "AMQP" as amqp
() "HTTP API" as http_api

rabbitmq_consumer -u-( amqp
lib_api -u-( http_api
lib_api ..> library
rabbitmq_consumer ..> library

library --( library_repositories
library --( library_publisher

publisher -u- library_publisher
database -u- library_repositories

@enduml