@startuml
header Демо проект "частная библиотека"
title Диаграмма компонентов

node "Nginx server" {
() "nginx"
}

() "REST API" as REST_API

nginx -- REST_API: http

node "BackendServes"{
    component "Private library" as PL
    component "Consumer" as consumer
}

node "DatabaseServer"{
    component "PostgreSQL"  as PSQL
}

node "RabbitServer"{
    component "RabbitMQ"  as RMQ
}

component "Library_API"  as LAPI

RMQ -- consumer
PL --( library_repositories
PSQL -- library_repositories
PL --( library_publisher
library_publisher --> RMQ: cli
LAPI -- PL : have
REST_API -- LAPI : http

@enduml